
create table contacts (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  subject text,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
