
create table posts (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  author text,
  image_url text,
  category text
);
